analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - library_names
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_getters_setters
    - unrelated_type_equality_checks
    - valid_regexps
    - avoid_relative_lib_imports
    - null_closures
    - prefer_equal_for_default_values
    - prefer_is_empty
    - recursive_getters
    - unawaited_futures
    - no_duplicate_case_values
    - avoid_types_as_parameter_names
    - always_declare_return_types
    - void_checks
    - use_rethrow_when_possible
    - type_annotate_public_apis
    - prefer_iterable_whereType
    - avoid_slow_async_io
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_void_to_null
    - always_require_non_null_named_parameters
    - directives_ordering
    - empty_catches
    - only_throw_errors
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_typing_uninitialized_variables
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - use_function_type_syntax_for_parameters
    - use_string_buffers
    - use_to_and_as_if_applicable
    - use_full_hex_values_for_flutter_colors
    - prefer_spread_collections
    - prefer_inlined_adds
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_elements_to_conditional_expressions
    - diagnostic_describe_all_properties
    - unnecessary_parenthesis
    - prefer_collection_literals
    - prefer_const_declarations
    - prefer_null_aware_operators
    - library_prefixes
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_single_cascade_in_expression_statements
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - join_return_with_assignment
    - parameter_assignments
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - provide_deprecation_message
    - sort_child_properties_last
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_await_in_return
    - unsafe_html