name: single_base
description: Platform agnostic bloc and storage interfaces that don't depend on any framework.
version: 1.0.1+2
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/single_base
repository: https://github.com/modulovalue/single_base
issue_tracker: https://github.com/modulovalue/single_base/issues

environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  meta: "^1.1.7"

dev_dependencies:
  test: "^1.6.6"
  extra_pedantic: "^1.0.0"